name = "PackageAnalyzer"
uuid = "e713c705-17e4-4cec-abe0-95bf5bf3e10c"
authors = ["Mos√® Giordano <mose@gnu.org>"]
version = "1.0.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
LicenseCheck = "726dbf0d-6eb6-41af-b36c-cd770e0f00cc"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
RegistryInstances = "2792f1a3-b283-48e8-9a74-f99dce5104f3"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
Tokei_jll = "3ac119c9-1236-5556-b556-adc8150b0244"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
CodecZlib = "0.7"
Git = "1.2.1"
GitHub = "5.4"
JSON3 = "1.5.1"
JuliaSyntax = "0.2"
LicenseCheck = "0.2"
RegistryInstances = "0.1"
julia = "1.6"

[extras]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JLLWrappers", "Test"]
