name = "AnalyzeRegistry"
uuid = "e713c705-17e4-4cec-abe0-95bf5bf3e10c"
authors = ["Mos√® Giordano <mose@gnu.org>"]
version = "0.1.0"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
BangBang = "198e06fe-97b7-11e9-32a5-e1d131e6ad66"
FLoops = "cc61a311-1640-44b5-9fba-1b764f453329"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LicenseCheck = "726dbf0d-6eb6-41af-b36c-cd770e0f00cc"
MicroCollections = "128add7d-3638-4c79-886c-908ea0c25c34"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Tokei_jll = "3ac119c9-1236-5556-b556-adc8150b0244"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
Arrow = "1.2.4"
BangBang = "0.3.29"
FLoops = "0.1.6"
JSON3 = "1.5.1"
LicenseCheck = "0.2"
MicroCollections = "0.1.0"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
